import NextHead from "next/head";

export default function Head() {
   return (
      <NextHead>
         <title>Quotes</title>
         <meta content="width=device-width, initial-scale=1" name="viewport" />
         <meta name="description" content="Generated by create next app" />
         <link rel="icon" href="/favicon.ico" />
         {/* <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js"></script> */}
      </NextHead>
   );
}
